-- Seed data for the house. Idempotent: safe to run on every branch and after every migration.
-- Seed: the fifteen domains, their relationships and three open seats each.
-- Danish names follow the landing page; English names follow the house
-- bundle. Domains 04 and 10 carry two candidate names in the prototype;
-- the landing's Danish name is used here until Kim decides.

insert into public.domains (id, sort_order, slug, name, tagline, blurb, house_description, skills, description, typical_tasks, target_seats) values
('mentor', 1, 'mentor-coach',
  '{"da":"Mentor & Coach","en":"Mentor & Coach"}',
  '{"da":"Sparring, der holder, når presset stiger.","en":"Sparring that holds when the pressure rises."}',
  '{"da":"Sparring for ejerledere og nye chefer — fast kadence, ingen kursusmappe.","en":"Sparring for owner-managers and first-time leaders — a fixed cadence, no course binder."}',
  '{"da":"Mentor- og coachforløb for ejerledere og nye chefer.","en":"Mentoring and coaching for owner-managers and first-time leaders."}',
  '{"da":["Mentorforløb","Coaching","Ejerledere"],"en":["Leadership","Coaching","Founder support"]}',
  '{"da":"Ejerledere og nye chefer står ofte alene med de beslutninger, der fylder mest. Domænet giver en fast sparringspartner med egen ledererfaring: en, der selv har ansat, afskediget, forhandlet og sagt nej.\n\nForløbene kører i en fast kadence, typisk hver anden uge, og handler om det, der ligger på bordet lige nu. Ingen kursusmappe, ingen model, der skal læres først.","en":"Owner-managers and first-time leaders are often alone with the decisions that weigh most. The domain provides a standing sparring partner with leadership experience of their own: someone who has hired, let go, negotiated and said no.\n\nEngagements run at a fixed cadence, typically every other week, and deal with what is on the table right now. No course binder, no model to learn first."}',
  '{"da":["Fast sparring for ejerledere","Onboarding af nye ledere","Forberedelse af svære samtaler","Generationsskifte i ejerledede virksomheder","Ledergruppens samarbejde"],"en":["Standing sparring for owner-managers","Onboarding first-time leaders","Preparing difficult conversations","Succession in owner-led companies","How the leadership team works together"]}', 3),
('salg', 2, 'salg-marketing',
  '{"da":"Salg & Marketing","en":"Sales & Marketing"}',
  '{"da":"Salg, der ikke afhænger af én person.","en":"Sales that do not hinge on one person."}',
  '{"da":"Pipeline, key accounts og kampagner — fra strategi til lukket aftale.","en":"Pipeline, key accounts and campaigns — strategy through signature."}',
  '{"da":"Pipeline, key accounts og kampagner.","en":"Pipeline, key accounts and campaigns."}',
  '{"da":["Pipeline","Key accounts","Kampagner"],"en":["Sales strategy","Pipeline","Key accounts"]}',
  '{"da":"Mange virksomheder sælger godt, så længe stifteren selv sidder med kunden. Domænet bygger det salg, der holder, når andre skal drive det: pipeline, key accounts og kampagner med en tydelig linje fra første kontakt til underskrift.\n\nSpecialisterne har selv haft budgetansvar. De går ind i salgsarbejdet, ikke kun i planen for det, og efterlader en proces, jeres egne folk kan køre videre.","en":"Many companies sell well as long as the founder sits with the customer. The domain builds the sales that hold when others have to run them: pipeline, key accounts and campaigns with a clear line from first contact to signature.\n\nThe specialists have carried a number themselves. They step into the selling, not only the plan for it, and leave behind a process your own people can run."}',
  '{"da":["Opbygning af pipeline og salgsproces","Key account-planer for de vigtigste kunder","Kampagner fra strategi til lukket aftale","Prissætning og tilbudsarbejde","Træning af egne sælgere"],"en":["Building pipeline and sales process","Key account plans for the most important customers","Campaigns from strategy to closed deal","Pricing and proposals","Training your own sales people"]}', 3),
('bestyrelse', 3, 'bestyrelse',
  '{"da":"Bestyrelse","en":"Board & Governance"}',
  '{"da":"En bestyrelse, der gør en forskel.","en":"A board that earns its seat."}',
  '{"da":"Professionelle bestyrelsesmedlemmer til ejerledede virksomheder.","en":"Professional board members for owner-led companies."}',
  '{"da":"Professionelle bestyrelsesmedlemmer til ejerledede virksomheder.","en":"Professional board members for owner-led companies."}',
  '{"da":["Bestyrelsesarbejde","Governance","Strategi"],"en":["Board work","Governance","Strategy"]}',
  '{"da":"En bestyrelse i en ejerledet virksomhed skal gøre mere end at godkende regnskabet. Domænet leverer professionelle bestyrelsesmedlemmer og formænd, der stiller de spørgsmål, ejeren ikke selv får stillet, og som følger op.\n\nSpecialisterne kender de dilemmaer, der er særlige for ejerledede virksomheder: ejerens dobbeltrolle, generationsskifte og den vækst, der kræver kapital udefra.","en":"A board in an owner-led company has to do more than approve the accounts. The domain provides professional board members and chairs who ask the questions the owner does not get asked, and who follow up.\n\nThe specialists know the dilemmas particular to owner-led companies: the owner''s double role, succession, and growth that needs outside capital."}',
  '{"da":["Bestyrelsesmedlem eller formand","Etablering af den første professionelle bestyrelse","Strategiarbejde med ejer og direktion","Forberedelse til generationsskifte eller salg","Bestyrelsesevaluering og governance"],"en":["Board member or chair","Establishing a first professional board","Strategy work with owner and management","Preparing for succession or a sale","Board evaluation and governance"]}', 3),
('invest', 4, 'investering-projekt',
  '{"da":"Investering & Projekt","en":"Investment & Finance"}',
  '{"da":"Kapital og business case, før beslutningen.","en":"Capital and the business case, before the decision."}',
  '{"da":"Kapitalrejsning, business cases og projektøkonomi.","en":"Fundraising, business cases and project finance."}',
  '{"da":"Kapitalrejsning og projektøkonomi.","en":"Fundraising and project finance."}',
  '{"da":["Kapitalrejsning","Projektøkonomi","Business case"],"en":["Funding","Business cases","Financial models"]}',
  '{"da":"Før en stor beslutning skal tallene holde: business casen, finansieringen og projektøkonomien. Domænet regner efter, udfordrer antagelserne og gør materialet klar til bank, investor eller bestyrelse.\n\nSpecialisterne har siddet på begge sider af bordet, som økonomichefer, investorer og projektejere. De ved, hvad en långiver spørger om, og hvad et projekt typisk undervurderer.","en":"Before a large decision the numbers have to hold: the business case, the financing and the project economics. The domain checks the figures, challenges the assumptions and prepares the material for bank, investor or board.\n\nThe specialists have sat on both sides of the table, as CFOs, investors and project owners. They know what a lender asks and what a project typically underestimates."}',
  '{"da":["Business case og finansiel model","Kapitalrejsning og investormateriale","Projektøkonomi og opfølgning","Køb og salg af virksomhed","Likviditetsstyring i vækst"],"en":["Business case and financial model","Fundraising and investor material","Project economics and follow-up","Buying and selling a company","Cash management in growth"]}', 3),
('consulting', 5, 'consulting',
  '{"da":"Consulting","en":"Consulting"}',
  '{"da":"Analyse, der ender i en beslutning.","en":"Analysis that ends in a decision."}',
  '{"da":"Analyse og beslutningsstøtte i korte forløb.","en":"Analysis and decision support in short engagements."}',
  '{"da":"Korte forløb med beslutningsstøtte.","en":"Short engagements with decision support."}',
  '{"da":["Analyse","Beslutningsstøtte","Korte forløb"],"en":["Analysis","Decision support","Business planning"]}',
  '{"da":"Nogle spørgsmål kræver en uge, ikke et halvt år. Domænet laver korte, afgrænsede analyser, der ender i en beslutning: markedet, kunderne, organisationen eller økonomien i en konkret sag.\n\nSpecialisterne arbejder alene eller to og to, tæt på ledelsen, og afleverer et materiale, der kan bruges direkte i beslutningen. Ikke en rapport, der skal oversættes først.","en":"Some questions need a week, not half a year. The domain runs short, bounded analyses that end in a decision: the market, the customers, the organisation or the economics of one concrete case.\n\nThe specialists work alone or in pairs, close to management, and hand over material that can be used directly in the decision. Not a report that needs translating first."}',
  '{"da":["Markeds- og kundeanalyse","Beslutningsgrundlag til direktion og bestyrelse","Forretningsplan og budget","Organisationsgennemgang","Second opinion på en strategi"],"en":["Market and customer analysis","Decision material for management and board","Business plan and budget","Organisation review","Second opinion on a strategy"]}', 3),
('ai', 6, 'ai-it',
  '{"da":"AI & IT","en":"AI & IT"}',
  '{"da":"AI, der kommer i drift.","en":"AI that reaches production."}',
  '{"da":"Løsningsarkitektur, maskinlæring i drift og dataplatforme.","en":"Solution architecture, machine learning in production and data platforms."}',
  '{"da":"Løsningsarkitektur, ML i drift og dataplatforme.","en":"Solution architecture, ML in production and data platforms."}',
  '{"da":["Løsningsarkitektur","ML i drift","Dataplatforme"],"en":["AI implementation","Data platforms","Software architecture"]}',
  '{"da":"Det er ikke svært at lave en demo med AI. Det svære er at få den i drift: data, der kan stoles på, en arkitektur, der holder, og en løsning, organisationen faktisk bruger. Domænet arbejder hele vejen fra idé til drift.\n\nSpecialisterne er arkitekter og udviklere med produktionserfaring. De rådgiver om, hvor AI giver værdi, og hvor det ikke gør, og bygger det, der skal bygges, sammen med jeres egne folk.","en":"Building a demo with AI is not hard. Getting it into production is: data that can be trusted, an architecture that holds, and a solution the organisation actually uses. The domain works the whole way from idea to operation.\n\nThe specialists are architects and developers with production experience. They advise on where AI adds value and where it does not, and build what needs building together with your own people."}',
  '{"da":["Afklaring: hvor giver AI værdi hos jer","Løsningsarkitektur og valg af platform","Sprogmodeller og agenter i drift","Dataplatform og datakvalitet","Sparring med jeres udviklere"],"en":["Clarifying where AI adds value for you","Solution architecture and platform choice","Language models and agents in production","Data platform and data quality","Sparring with your developers"]}', 3),
('hr', 7, 'hr-rekruttering',
  '{"da":"HR & Rekruttering","en":"HR & Recruitment"}',
  '{"da":"En HR-afdeling på deltid, når I ikke skal have en hel.","en":"An HR department part-time, when a whole one is too much."}',
  '{"da":"Ansættelser, employer branding og HR-jura på deltid.","en":"Hiring, employer branding and part-time HR counsel."}',
  '{"da":"Ansættelser, employer branding og HR-jura.","en":"Hiring, employer branding and HR counsel."}',
  '{"da":["Ansættelser","Employer branding","HR-jura"],"en":["Recruitment","People operations","Employer branding"]}',
  '{"da":"Virksomheder med 20 til 200 ansatte har brug for HR, men sjældent for en hel afdeling. Domænet leverer den på deltid: rekruttering, ansættelsesret, personalehåndbog og de samtaler, ledere helst udskyder.\n\nSpecialisterne har været HR-chefer og rekrutteringspartnere. De kommer ind på faste dage eller i en konkret proces og sørger for, at det, der bliver aftalt, også bliver gjort.","en":"Companies of 20 to 200 employees need HR, but rarely a whole department. The domain delivers it part-time: recruitment, employment law, the staff handbook and the conversations managers prefer to postpone.\n\nThe specialists have been HR managers and recruitment partners. They come in on fixed days or for one concrete process, and make sure that what is agreed also gets done."}',
  '{"da":["Rekruttering af nøglemedarbejdere","HR-chef på deltid","Personalehåndbog og ansættelseskontrakter","Employer branding og onboarding","Håndtering af svære personalesager"],"en":["Recruiting key employees","Part-time HR manager","Staff handbook and employment contracts","Employer branding and onboarding","Handling difficult personnel cases"]}', 3),
('advisory', 8, 'advisory',
  '{"da":"Advisory","en":"Advisory"}',
  '{"da":"Rådgivning i direktionens højde.","en":"Advice at executive altitude."}',
  '{"da":"Rådgivning på direktionsniveau — ESG, risiko og rapportering.","en":"Board-level advisory — ESG, risk and reporting."}',
  '{"da":"ESG, risiko og rapportering.","en":"ESG, risk and reporting."}',
  '{"da":["ESG","Risiko","Rapportering"],"en":["ESG","Risk","Reporting"]}',
  '{"da":"Krav om ESG, risikostyring og rapportering rammer nu også mellemstore virksomheder. Domænet rådgiver direktion og bestyrelse om, hvad der faktisk kræves, hvad der kan vente, og hvordan det bliver til rutine i stedet for et årligt projekt.\n\nSpecialisterne har baggrund i revision, compliance og direktionsarbejde. De taler både bestyrelsens og bogholderiets sprog.","en":"Requirements on ESG, risk management and reporting now reach mid-sized companies too. The domain advises management and board on what is actually required, what can wait, and how it becomes routine instead of an annual project.\n\nThe specialists come from audit, compliance and executive roles. They speak both the board''s language and the bookkeeper''s."}',
  '{"da":["ESG-rapportering, der passer til virksomhedens størrelse","Risikoanalyse og beredskab","Rapportering til bestyrelse og ejere","Forberedelse til revision og due diligence","Politikker og kontroller"],"en":["ESG reporting sized to the company","Risk analysis and contingency","Reporting to board and owners","Preparing for audit and due diligence","Policies and controls"]}', 3),
('supply', 9, 'supply-chain-logistik',
  '{"da":"Supply Chain & Logistik","en":"Supply Chain & Logistics"}',
  '{"da":"Forsyningskæden, når den brænder.","en":"The supply chain, when it burns."}',
  '{"da":"Indkøb, lager og transport for producerende virksomheder.","en":"Sourcing, warehousing and transport for manufacturers."}',
  '{"da":"Indkøb, lager og transport for producerende virksomheder.","en":"Sourcing, warehousing and transport for manufacturers."}',
  '{"da":["Indkøb","Lager","Transport"],"en":["Procurement","Logistics","Inventory"]}',
  '{"da":"Når en leverandør svigter, eller lageret vokser, mærkes det på bundlinjen med det samme. Domænet arbejder med producerende virksomheders forsyningskæde: indkøb, lager, transport og de systemer, der binder dem sammen.\n\nSpecialisterne har selv drevet indkøb og logistik. De tager fat i det akutte først og efterlader en kæde, der kan tåle den næste forstyrrelse.","en":"When a supplier fails or the stock grows, the bottom line feels it at once. The domain works with manufacturers'' supply chains: sourcing, warehousing, transport and the systems that tie them together.\n\nThe specialists have run procurement and logistics themselves. They tackle the urgent first and leave behind a chain that can take the next disruption."}',
  '{"da":["Indkøbsstrategi og leverandørforhandling","Lagerstyring og varebeholdning","Transport og distribution","S&OP og planlægning","Forsyningskæden under omlægning eller vækst"],"en":["Sourcing strategy and supplier negotiation","Inventory management","Transport and distribution","S&OP and planning","The supply chain through change or growth"]}', 3),
('disruption', 10, 'disruption-innovation',
  '{"da":"Disruption & Innovation","en":"Innovation & New Ventures"}',
  '{"da":"Vækst, når den gamle model stopper.","en":"Growth when the old model stalls."}',
  '{"da":"Nye forretningsmodeller, når den nuværende holder op med at vokse.","en":"New business models when the current one stops growing."}',
  '{"da":"Nye forretningsmodeller og innovationsforløb.","en":"New business models and innovation work."}',
  '{"da":["Forretningsmodeller","Innovation","Nye ventures"],"en":["Innovation","New ventures","Business models"]}',
  '{"da":"Den forretningsmodel, der byggede virksomheden, holder på et tidspunkt op med at vokse. Domænet hjælper med at finde og teste den næste: nye kundegrupper, nye ydelser eller en helt ny forretning ved siden af den gamle.\n\nSpecialisterne har selv startet og solgt virksomheder. De arbejder i korte, konkrete forløb med hypoteser, der bliver prøvet af på rigtige kunder, før der investeres.","en":"The business model that built the company at some point stops growing. The domain helps find and test the next one: new customer groups, new services or a whole new business alongside the old.\n\nThe specialists have started and sold companies themselves. They work in short, concrete engagements with hypotheses tested on real customers before money is committed."}',
  '{"da":["Vurdering af den nuværende forretningsmodel","Nye ydelser og kundegrupper","Test af idéer på rigtige kunder","Opstart af ny forretning ved siden af driften","Innovationsforløb med ledelsen"],"en":["Assessing the current business model","New services and customer groups","Testing ideas on real customers","Starting a new business alongside operations","Innovation programmes with management"]}', 3),
('digital', 11, 'digital-web-markedsfoering',
  '{"da":"Digital Web & Markedsføring","en":"Digital & Marketing"}',
  '{"da":"Web og kampagner, der kan måles.","en":"Web and campaigns you can measure."}',
  '{"da":"Web, performance, automation og identitet.","en":"Web, performance, automation and identity."}',
  '{"da":"Web, performance, automation og identitet.","en":"Web, performance, automation and identity."}',
  '{"da":["Web","Performance","Automation"],"en":["Web design","Performance marketing","Automation"]}',
  '{"da":"Et website og en kampagne skal kunne måles, ellers er de en udgift. Domænet arbejder med web, performance marketing, automation og visuel identitet, med tal på, hvad det giver.\n\nSpecialisterne er praktikere, der selv bygger og driver. De sætter måling op fra starten og rapporterer på det, der betyder noget for forretningen, ikke på klik.","en":"A website and a campaign have to be measurable, otherwise they are a cost. The domain works with web, performance marketing, automation and visual identity, with numbers on what it returns.\n\nThe specialists are practitioners who build and run things themselves. They set up measurement from the start and report on what matters to the business, not on clicks."}',
  '{"da":["Website og webshop","Performance marketing og annoncering","Marketing automation og e-mail","Visuel identitet og brand","Måling og rapportering"],"en":["Website and webshop","Performance marketing and advertising","Marketing automation and email","Visual identity and brand","Measurement and reporting"]}', 3),
('projekt', 12, 'projektledelse',
  '{"da":"Projektledelse","en":"Project Management"}',
  '{"da":"Projekter, der faktisk lander.","en":"Projects that actually land."}',
  '{"da":"Projektledere til implementeringer, der skal i drift.","en":"Project managers for implementations that have to go live."}',
  '{"da":"Projektledelse af implementeringer, der skal i drift.","en":"Project management for implementations that have to go live."}',
  '{"da":["Projektledelse","Implementering","Drift"],"en":["Delivery","Implementation","Change"]}',
  '{"da":"De fleste projekter fejler ikke på idéen, men på vejen i drift. Domænet leverer projektledere til implementeringer, der skal lande: nye systemer, nye processer, nye fabrikker.\n\nSpecialisterne har ledet projekter fra begge sider, som leverandør og som kunde. De holder plan, budget og interessenter samlet og siger til i tide, når noget skrider.","en":"Most projects do not fail on the idea but on the way into operation. The domain provides project managers for implementations that have to land: new systems, new processes, new plants.\n\nThe specialists have led projects from both sides, as supplier and as customer. They keep plan, budget and stakeholders together and speak up in time when something slips."}',
  '{"da":["Projektledelse af systemimplementering","Programledelse på tværs af afdelinger","Opstart og redning af projekter","Interessent- og leverandørstyring","Projektkontor og metode"],"en":["Project management of system implementations","Programme management across departments","Starting and rescuing projects","Stakeholder and supplier management","Project office and method"]}', 3),
('management', 13, 'management-consulting',
  '{"da":"Management Consulting","en":"Management Consulting"}',
  '{"da":"Drift og styring, uden et helt konsulenthus.","en":"Operations and governance without a whole consultancy."}',
  '{"da":"Organisation, drift og styring for virksomheder mellem 50 og 500 ansatte.","en":"Organisation, operations and governance for companies of 50 to 500."}',
  '{"da":"Organisation og styring for virksomheder mellem 50 og 500 ansatte.","en":"Organisation and governance for companies of 50 to 500."}',
  '{"da":["Organisation","Styring","Drift"],"en":["Organisation","Operating models","Strategy"]}',
  '{"da":"Virksomheder med 50 til 500 ansatte har de samme udfordringer som de store, men ikke de samme stabsfunktioner. Domænet arbejder med organisation, drift og styring: hvem beslutter hvad, hvordan der følges op, og hvor tiden går tabt.\n\nSpecialisterne har været direktører og driftschefer. De arbejder med ledelsen i faste forløb og med konkrete ændringer, der kan ses i driften inden for et kvartal.","en":"Companies of 50 to 500 employees have the same challenges as the large ones, but not the same staff functions. The domain works with organisation, operations and governance: who decides what, how follow-up works, and where time is lost.\n\nThe specialists have been managing directors and heads of operations. They work with management in fixed engagements and on concrete changes visible in operations within a quarter."}',
  '{"da":["Organisationsdesign og ansvarsfordeling","Styringsmodel og målopfølgning","Driftsforbedring og procesgennemgang","Interim ledelse","Ledergruppens arbejdsform"],"en":["Organisation design and accountability","Governance model and target follow-up","Operational improvement and process review","Interim management","How the leadership team works"]}', 3),
('juridisk', 14, 'juridisk-raadgiver',
  '{"da":"Juridisk Rådgiver","en":"Legal Advisory"}',
  '{"da":"Kontrakter og GDPR uden et advokatkontor.","en":"Contracts and GDPR without a law firm."}',
  '{"da":"Kontrakter, GDPR og NIS2 for små og mellemstore virksomheder.","en":"Contracts, GDPR and NIS2 for small and mid-sized companies."}',
  '{"da":"Kontrakter, GDPR og NIS2.","en":"Contracts, GDPR and NIS2."}',
  '{"da":["Kontrakter","GDPR","NIS2"],"en":["Contracts","GDPR","Compliance"]}',
  '{"da":"Kontrakter, GDPR og NIS2 kræver jura, men ikke altid et advokatkontor. Domænet leverer juridisk rådgivning til små og mellemstore virksomheder i et sprog, der kan bruges i hverdagen.\n\nSpecialisterne er jurister med erfaring fra virksomheder, ikke kun fra kontorer. De ved, hvad der er nødvendigt, og hvad der er rart at have, og skriver aftaler, som begge parter forstår.","en":"Contracts, GDPR and NIS2 need legal skill, but not always a law firm. The domain provides legal advice to small and mid-sized companies, in language that works day to day.\n\nThe specialists are lawyers with experience from inside companies, not only from firms. They know what is necessary and what is nice to have, and write agreements both parties understand."}',
  '{"da":["Kunde- og leverandørkontrakter","GDPR: politikker, databehandleraftaler og praksis","NIS2 og krav til it-sikkerhed","Ansættelsesretlige spørgsmål","Juridisk sparring på deltid"],"en":["Customer and supplier contracts","GDPR: policies, processing agreements and practice","NIS2 and IT security requirements","Employment law questions","Part-time legal sparring"]}', 3),
('automation', 15, 'automation-produktion',
  '{"da":"Automation & Produktion","en":"Automation & Production"}',
  '{"da":"Produktion, der kører selv, hvor den kan.","en":"Production that runs itself where it can."}',
  '{"da":"Robotter, OEE og produktionsdata på fabriksgulvet.","en":"Robots, OEE and production data on the factory floor."}',
  '{"da":"Robotter, OEE og produktionsdata på fabriksgulvet.","en":"Robots, OEE and production data on the factory floor."}',
  '{"da":["Robotter","OEE","Produktionsdata"],"en":["Robotics","Production data","Process improvement"]}',
  '{"da":"På fabriksgulvet er der sjældent tid til at eksperimentere. Domænet arbejder med automation og produktion: robotter, OEE og de produktionsdata, der viser, hvor timerne og materialet går hen.\n\nSpecialisterne har selv stået i produktionen, som produktionschefer og automationsingeniører. De starter med det, der stopper flowet i dag, og bygger derfra.","en":"On the factory floor there is rarely time to experiment. The domain works with automation and production: robots, OEE and the production data that shows where the hours and the material go.\n\nThe specialists have stood in production themselves, as production managers and automation engineers. They start with what stops the flow today and build from there."}',
  '{"da":["OEE-måling og flaskehalse","Robotter og automatisering af arbejdsstationer","Produktionsdata og dashboards","Lean og løbende forbedringer","Investeringsgrundlag for nyt udstyr"],"en":["OEE measurement and bottlenecks","Robots and workstation automation","Production data and dashboards","Lean and continuous improvement","Investment cases for new equipment"]}', 3)
on conflict (id) do update set
  name = excluded.name, tagline = excluded.tagline, blurb = excluded.blurb,
  house_description = excluded.house_description, skills = excluded.skills,
  description = excluded.description, typical_tasks = excluded.typical_tasks;

-- Neighbour pairs, normalised so domain_a < domain_b.
insert into public.domain_relationships (domain_a, domain_b)
select least(a, b), greatest(a, b) from (values
  ('ai','salg'),('ai','digital'),('ai','hr'),('ai','consulting'),('ai','invest'),('ai','management'),
  ('salg','digital'),('salg','projekt'),('salg','advisory'),('digital','mentor'),('digital','bestyrelse'),
  ('hr','mentor'),('hr','juridisk'),('hr','management'),('consulting','advisory'),('consulting','supply'),
  ('consulting','disruption'),('invest','bestyrelse'),('invest','juridisk'),('invest','automation'),
  ('management','projekt'),('management','disruption'),('supply','automation'),('supply','disruption'),
  ('advisory','bestyrelse'),('projekt','mentor')
) as pairs(a, b)
on conflict do nothing;

-- Three open seats per domain.
insert into public.seats (domain_id, position, status)
select d.id, p, 'open'
from public.domains d, generate_series(1, 3) as p
on conflict (domain_id, position) do nothing;
