import type { I18nText } from "@/lib/i18n";

/** Interface copy for the admin pages. Danish first; the board reads Danish. */
export const admin = {
  nav: {
    overview: { da: "Oversigt", en: "Overview" } as I18nText,
    applications: { da: "Ansøgninger", en: "Applications" } as I18nText,
    contacts: { da: "Henvendelser", en: "Enquiries" } as I18nText,
    access: { da: "Adgang", en: "Access" } as I18nText,
    domains: { da: "Domæner", en: "Domains" } as I18nText,
    seats: { da: "Pladser", en: "Seats" } as I18nText,
    people: { da: "Personer", en: "People" } as I18nText,
    numbers: { da: "Tal", en: "Numbers" } as I18nText,
    log: { da: "Log", en: "Log" } as I18nText,
  },
  common: {
    save: { da: "Gem", en: "Save" } as I18nText,
    saving: { da: "Gemmer…", en: "Saving…" } as I18nText,
    saved: { da: "Gemt.", en: "Saved." } as I18nText,
    failed: { da: "Kunne ikke gemme. Prøv igen.", en: "Could not save. Try again." } as I18nText,
    forbidden: { da: "Kun admin må gøre det.", en: "Only admin may do that." } as I18nText,
    none: { da: "Ingen endnu.", en: "None yet." } as I18nText,
    back: { da: "Tilbage", en: "Back" } as I18nText,
    all: { da: "Alle", en: "All" } as I18nText,
    yes: { da: "Ja", en: "Yes" } as I18nText,
    no: { da: "Nej", en: "No" } as I18nText,
    da: { da: "Dansk", en: "Danish" } as I18nText,
    en: { da: "Engelsk", en: "English" } as I18nText,
    created: { da: "Oprettet", en: "Created" } as I18nText,
    domain: { da: "Domæne", en: "Domain" } as I18nText,
    name: { da: "Navn", en: "Name" } as I18nText,
    email: { da: "E-mail", en: "Email" } as I18nText,
    status: { da: "Status", en: "Status" } as I18nText,
    language: { da: "Sprog", en: "Language" } as I18nText,
  },
  overview: {
    title: { da: "Husets {em}kontor{/em}", en: "The house {em}office{/em}" } as I18nText,
    intro: {
      da: "Ansøgninger, henvendelser, domænetekster, pladser og roller. Alt, der ændres her, står i loggen.",
      en: "Applications, enquiries, domain copy, seats and roles. Everything changed here is in the log.",
    } as I18nText,
    newApplications: { da: "Nye ansøgninger", en: "New applications" } as I18nText,
    openContacts: { da: "Ubesvarede henvendelser", en: "Unanswered enquiries" } as I18nText,
    openAccess: { da: "Anmodninger om adgang", en: "Access requests" } as I18nText,
    recruiting: { da: "Domæner der søger", en: "Domains recruiting" } as I18nText,
    people: { da: "Personer med adgang", en: "People with access" } as I18nText,
  },
  applications: {
    title: { da: "Ansøgninger", en: "Applications" } as I18nText,
    intro: {
      da: "Fra freelancer-siden. Sæt status, skriv noter, afgør. Afslag slettes automatisk efter seks måneder (senere).",
      en: "From the freelancer page. Set status, write notes, decide. Declines are deleted after six months (later).",
    } as I18nText,
    filter: { da: "Vis", en: "Show" } as I18nText,
    status: {
      received: { da: "Modtaget", en: "Received" },
      interview: { da: "Til samtale", en: "Interview" },
      accepted: { da: "Optaget", en: "Accepted" },
      declined: { da: "Afslag", en: "Declined" },
      on_hold: { da: "På hold", en: "On hold" },
    } as Record<string, I18nText>,
    fields: {
      craft: { da: "Fag", en: "Craft" } as I18nText,
      years: { da: "År i faget", en: "Years in the craft" } as I18nText,
      phone: { da: "Telefon", en: "Phone" } as I18nText,
      linkedin: { da: "LinkedIn", en: "LinkedIn" } as I18nText,
      cases: { da: "To cases", en: "Two cases" } as I18nText,
      reference: { da: "Reference", en: "Reference" } as I18nText,
      message: { da: "Besked", en: "Message" } as I18nText,
      decided: { da: "Afgjort", en: "Decided" } as I18nText,
    },
    setStatus: { da: "Sæt status", en: "Set status" } as I18nText,
    notes: { da: "Interne noter", en: "Internal notes" } as I18nText,
    addNote: { da: "Tilføj note", en: "Add note" } as I18nText,
    notePlaceholder: { da: "Fra samtalen, referencer, næste skridt…", en: "From the interview, references, next step…" } as I18nText,
    acceptedHint: {
      da: "Optaget: reservér en plads under Pladser og giv rollen specialist under Personer. Invitationen (2.3) kommer.",
      en: "Accepted: reserve a seat under Seats and grant the specialist role under People. The invitation (2.3) is coming.",
    } as I18nText,
  },
  contacts: {
    title: { da: "Henvendelser", en: "Enquiries" } as I18nText,
    intro: {
      da: "Fra kontaktblokken. Svar fra din egen mail (afsenderen står i mailen, du fik), og markér som besvaret her.",
      en: "From the contact block. Reply from your own mail (the sender is in the notice you got) and mark as handled here.",
    } as I18nText,
    open: { da: "Ubesvarede", en: "Open" } as I18nText,
    handled: { da: "Besvarede", en: "Handled" } as I18nText,
    company: { da: "Virksomhed", en: "Company" } as I18nText,
    markHandled: { da: "Markér som besvaret", en: "Mark as handled" } as I18nText,
    reopen: { da: "Åbn igen", en: "Reopen" } as I18nText,
    handledAt: { da: "Besvaret", en: "Handled" } as I18nText,
    note: { da: "Intern note", en: "Internal note" } as I18nText,
  },
  access: {
    title: { da: "Adgang til CV'er", en: "Access to CVs" } as I18nText,
    intro: {
      da: "Kunder, der har bedt om at læse de fulde CV'er. Godkend, og de får rollen kunde, en konto og en mail med login. Afslå, og de får en venlig mail.",
      en: "Clients who asked to read the full CVs. Approve, and they get the client role, an account and a sign-in mail. Decline, and they get a polite mail.",
    } as I18nText,
    open: { da: "Ubesvarede", en: "Open" } as I18nText,
    decided: { da: "Afgjorte", en: "Decided" } as I18nText,
    status: {
      received: { da: "Modtaget", en: "Received" },
      approved: { da: "Godkendt", en: "Approved" },
      declined: { da: "Afslået", en: "Declined" },
    } as Record<string, I18nText>,
    lookingFor: { da: "Leder efter", en: "Looking for" } as I18nText,
    cameFrom: { da: "Kom fra", en: "Came from" } as I18nText,
    approve: { da: "Godkend og giv adgang", en: "Approve and grant access" } as I18nText,
    decline: { da: "Afslå", en: "Decline" } as I18nText,
    approved: { da: "Godkendt. Kunden har fået mail med login.", en: "Approved. The client got a sign-in mail." } as I18nText,
    declined: { da: "Afslået. Der er sendt en mail.", en: "Declined. A mail went out." } as I18nText,
    note: { da: "Intern note", en: "Internal note" } as I18nText,
  },
  domains: {
    title: { da: "Domæner", en: "Domains" } as I18nText,
    intro: {
      da: "Navne, taglines og tekster på dansk og engelsk. Ændringer er på forsiden og domænesiden inden for et minut.",
      en: "Names, taglines and copy in Danish and English. Changes reach the landing and domain pages within a minute.",
    } as I18nText,
    edit: { da: "Redigér", en: "Edit" } as I18nText,
    fields: {
      name: { da: "Navn", en: "Name" } as I18nText,
      slug: { da: "Slug (i adressen)", en: "Slug (in the address)" } as I18nText,
      tagline: { da: "Tagline", en: "Tagline" } as I18nText,
      blurb: { da: "Beskrivelse (domænesiden)", en: "Blurb (domain page)" } as I18nText,
      houseDescription: { da: "Tekst i vinduet (huset)", en: "Text in the window (house)" } as I18nText,
      skills: { da: "Kompetencer, én per linje", en: "Skills, one per line" } as I18nText,
      targetSeats: { da: "Pladser i alt (mål)", en: "Target seats" } as I18nText,
      override: { da: "Status på huset", en: "Status on the house" } as I18nText,
      overrideAuto: { da: "Automatisk (efter pladser)", en: "Automatic (from seats)" } as I18nText,
      published: { da: "Vist på sitet", en: "Shown on the site" } as I18nText,
    },
  },
  seats: {
    title: { da: "Pladser", en: "Seats" } as I18nText,
    intro: {
      da: "Hver plads er en række. Aktive pladser tæller mod målet; et domæne søger, indtil det når målet. Pladser med en person slettes ikke; luk dem.",
      en: "Each seat is a row. Active seats count towards the target; a domain recruits until it reaches it. Seats with a person are not deleted; close them.",
    } as I18nText,
    status: {
      open: { da: "Åben", en: "Open" },
      reserved: { da: "Reserveret", en: "Reserved" },
      active: { da: "Aktiv", en: "Active" },
      notice: { da: "Opsagt", en: "Notice" },
      closed: { da: "Lukket", en: "Closed" },
    } as Record<string, I18nText>,
    position: { da: "Plads", en: "Seat" } as I18nText,
    holder: { da: "Person (e-mail)", en: "Person (email)" } as I18nText,
    paid: { da: "Indskud betalt", en: "Buy-in paid" } as I18nText,
    noticeGiven: { da: "Opsagt den", en: "Notice given" } as I18nText,
    endsAt: { da: "Slutter", en: "Ends" } as I18nText,
    note: { da: "Note (vises ved åbne pladser)", en: "Note (shown for open seats)" } as I18nText,
    add: { da: "Tilføj pladser", en: "Add seats" } as I18nText,
    count: { da: "Antal", en: "Count" } as I18nText,
    remove: { da: "Fjern", en: "Remove" } as I18nText,
    removeHint: { da: "Kun tomme åbne eller lukkede pladser kan fjernes.", en: "Only empty open or closed seats can be removed." } as I18nText,
    summary: { da: "{active} aktive af {target} · {open} åbne", en: "{active} active of {target} · {open} open" } as I18nText,
    unknownHolder: { da: "Ingen person med den e-mail. Opret under Personer først.", en: "No person with that email. Create them under People first." } as I18nText,
    full: { da: "Der er allerede tolv pladser.", en: "There are already twelve seats." } as I18nText,
  },
  people: {
    title: { da: "Personer og roller", en: "People and roles" } as I18nText,
    intro: {
      da: "Hvem har adgang til hvad. At give en rolle opretter kontoen; personen logger ind med et link fra /log-ind, når de vil. Der sendes ingen mail herfra.",
      en: "Who has access to what. Granting a role creates the account; the person signs in with a link from /log-ind when they like. No mail is sent from here.",
    } as I18nText,
    grant: { da: "Giv rolle", en: "Grant role" } as I18nText,
    role: { da: "Rolle", en: "Role" } as I18nText,
    revoke: { da: "Fjern", en: "Revoke" } as I18nText,
    account: { da: "Konto", en: "Account" } as I18nText,
    linked: { da: "Oprettet", en: "Created" } as I18nText,
    notLinked: { da: "Ingen konto", en: "No account" } as I18nText,
    adminOnly: { da: "Roller ændres kun af admin.", en: "Only admin changes roles." } as I18nText,
    domainRequired: { da: "Specialist og domæneansvarlig kræver et domæne.", en: "Specialist and domain lead need a domain." } as I18nText,
    noDomain: { da: "Den rolle tager ikke et domæne.", en: "That role takes no domain." } as I18nText,
  },
  numbers: {
    title: { da: "Tal fra huset", en: "Numbers from the house" } as I18nText,
    intro: {
      da: "Seneste 30 dage per domæne, fra husets egne besøgstal. Ingen tredjeparts-sporing.",
      en: "Last 30 days per domain, from the house's own event capture. No third-party tracking.",
    } as I18nText,
    views: { da: "Visninger", en: "Views" } as I18nText,
    hovers: { da: "Vinduer åbnet", en: "Windows opened" } as I18nText,
    visitors: { da: "Besøgende", en: "Visitors" } as I18nText,
    contacts: { da: "Henvendelser", en: "Enquiries" } as I18nText,
    applications: { da: "Ansøgninger", en: "Applications" } as I18nText,
  },
  log: {
    title: { da: "Log", en: "Log" } as I18nText,
    intro: {
      da: "De seneste 200 ændringer: hvem, hvad, hvornår. Tomt navn betyder et script med projektnøglen.",
      en: "The latest 200 changes: who, what, when. An empty name means a script with the project key.",
    } as I18nText,
    when: { da: "Hvornår", en: "When" } as I18nText,
    who: { da: "Hvem", en: "Who" } as I18nText,
    what: { da: "Hvad", en: "What" } as I18nText,
    table: { da: "Tabel", en: "Table" } as I18nText,
  },
};
