import type { I18nText } from "@/lib/i18n";
import type { Role } from "@/lib/auth";

/** Interface copy for sign-in, the portal shell and the admin shell. */
export const auth = {
  /** "Se som": the admin-only role switcher next to the header logo. */
  viewAs: {
    label: { da: "Ser som", en: "Viewing as" } as I18nText,
    options: {
      admin: { da: "Admin (mig)", en: "Admin (me)" } as I18nText,
      board: { da: "Bestyrelse", en: "Board" } as I18nText,
      specialist: { da: "Specialist", en: "Specialist" } as I18nText,
      client: { da: "Kunde", en: "Client" } as I18nText,
      visitor: { da: "Besøgende", en: "Visitor" } as I18nText,
    },
  },
  login: {
    eyebrow: { da: "Log ind", en: "Sign in" } as I18nText,
    title: { da: "Ind i {em}huset{/em}", en: "Into the {em}house{/em}" } as I18nText,
    intro: {
      da: "Skriv din e-mail, så sender vi et link. Ingen adgangskode at huske.",
      en: "Enter your email and we send you a link. No password to remember.",
    } as I18nText,
    email: { da: "E-mail", en: "Email" } as I18nText,
    submit: { da: "Send link", en: "Send link" } as I18nText,
    sending: { da: "Sender…", en: "Sending…" } as I18nText,
    sentTitle: { da: "Tjek din indbakke.", en: "Check your inbox." } as I18nText,
    sentText: {
      da: "Hvis adressen har adgang til huset, er der et link på vej. Det virker i en time og kun én gang.",
      en: "If the address has access to the house, a link is on its way. It works for one hour and only once.",
    } as I18nText,
    again: { da: "Bed om et nyt link", en: "Ask for a new link" } as I18nText,
    noAccessTitle: { da: "Ingen adgang endnu?", en: "No access yet?" } as I18nText,
    noAccessText: {
      da: "Kunder får adgang til de fulde CV'er efter aftale med huset. Specialister får adgang, når de er optaget.",
      en: "Clients get access to the full CVs by agreement with the house. Specialists get access once admitted.",
    } as I18nText,
    contact: { da: "Skriv til huset", en: "Write to the house" } as I18nText,
    apply: { da: "Søg optagelse", en: "Apply for a seat" } as I18nText,
    errors: {
      email: { da: "Skriv en gyldig e-mailadresse.", en: "Enter a valid email address." } as I18nText,
      rate: { da: "Vent et minut, før du beder om et nyt link.", en: "Wait a minute before asking for a new link." } as I18nText,
      failed: { da: "Vi kunne ikke sende linket. Prøv igen om lidt.", en: "We could not send the link. Try again shortly." } as I18nText,
      link: { da: "Linket er brugt eller udløbet. Bed om et nyt.", en: "That link has been used or has expired. Ask for a new one." } as I18nText,
    },
  },
  portal: {
    nav: { da: "Portal", en: "Portal" } as I18nText,
    eyebrow: { da: "Portalen", en: "The portal" } as I18nText,
    hello: { da: "Hej {name}", en: "Hello {name}" } as I18nText,
    signedInAs: { da: "Logget ind som", en: "Signed in as" } as I18nText,
    yourRoles: { da: "Dine roller", en: "Your roles" } as I18nText,
    noRoles: {
      da: "Din konto er oprettet, men har ingen roller endnu. Skriv til huset, hvis det er en fejl.",
      en: "Your account exists but has no roles yet. Write to the house if that is a mistake.",
    } as I18nText,
    denied: { da: "Du har ikke adgang til den side.", en: "You do not have access to that page." } as I18nText,
    doorsTitle: { da: "Dine døre", en: "Your doors" } as I18nText,
    doors: {
      minSide: { da: "Min side", en: "My page" } as I18nText,
      minSideText: { da: "Din profil, dit CV, din ledighed.", en: "Your profile, your CV, your availability." } as I18nText,
      applications: { da: "Ansøgninger", en: "Applications" } as I18nText,
      applicationsText: { da: "Kø, samtaler, optagelse.", en: "Queue, interviews, admission." } as I18nText,
      contacts: { da: "Henvendelser", en: "Enquiries" } as I18nText,
      contactsText: { da: "Kunder, der har skrevet til huset.", en: "Clients who wrote to the house." } as I18nText,
      admin: { da: "Husets kontor", en: "The house office" } as I18nText,
      adminText: { da: "Domæner, pladser, personer, tal, log.", en: "Domains, seats, people, numbers, log." } as I18nText,
      site: { da: "Huset", en: "The house" } as I18nText,
      siteText: { da: "Forsiden, som kunderne ser den.", en: "The landing, as clients see it." } as I18nText,
    },
    signOut: { da: "Log ud", en: "Sign out" } as I18nText,
    toSite: { da: "Til forsiden", en: "To the site" } as I18nText,
    sidebar: {
      overview: { da: "Overblik", en: "Overview" } as I18nText,
      you: { da: "Dig", en: "You" } as I18nText,
      meetings: { da: "Møder", en: "Meetings" } as I18nText,
      queue: { da: "Kø", en: "Queue" } as I18nText,
      house: { da: "Huset", en: "The house" } as I18nText,
      office: { da: "Kontoret", en: "The office" } as I18nText,
    },
    dashboard: {
      eyebrow: { da: "Overblik", en: "Overview" } as I18nText,
      editProfile: { da: "Rediger profil", en: "Edit profile" } as I18nText,
      importLinkedIn: { da: "Hent fra LinkedIn", en: "Load from LinkedIn" } as I18nText,
      openQueue: { da: "Åbn køen", en: "Open the queue" } as I18nText,
      profileTitle: { da: "Din profil", en: "Your profile" } as I18nText,
      statusShort: {
        draft: { da: "Kladde", en: "Draft" },
        publishedNoSeat: { da: "Udgivet · plads ikke aktiv", en: "Published · seat not active" },
        live: { da: "Synlig", en: "Live" },
      } as Record<string, I18nText>,
      checklistTitle: { da: "Det, der mangler", en: "What is missing" } as I18nText,
      complete: { da: "Profilen er komplet.", en: "The profile is complete." } as I18nText,
      checklist: {
        title: { da: "Titel", en: "Title" },
        tagline: { da: "Én linje om dig", en: "One line about you" },
        city: { da: "By", en: "City" },
        years: { da: "År i faget", en: "Years in the craft" },
        summary: { da: "Om dig, mindst et par sætninger", en: "About you, at least a few sentences" },
        skills: { da: "Mindst tre kompetencer", en: "At least three skills" },
        languages: { da: "Sprog", en: "Languages" },
        rate: { da: "Takst", en: "Rate" },
        availability: { da: "Ledighed", en: "Availability" },
        links: { da: "LinkedIn eller hjemmeside", en: "LinkedIn or website" },
        portrait: { da: "Portræt", en: "Portrait" },
        experience: { da: "Mindst to stillinger", en: "At least two positions" },
        education: { da: "Uddannelse", en: "Education" },
      } as Record<string, I18nText>,
      requestsTitle: { da: "Mødeforespørgsler", en: "Meeting requests" } as I18nText,
      waiting: { da: "venter {age}", en: "waiting {age}" } as I18nText,
      awaitingClient: { da: "{n} afventer kundens svar på dit forslag.", en: "{n} awaiting the client's answer to your proposal." } as I18nText,
      noRequests: { da: "Ingen åbne forespørgsler. Du får en mail, når der kommer én.", en: "No open requests. You get a mail when one arrives." } as I18nText,
      nextMeeting: { da: "Næste møde", en: "Next meeting" } as I18nText,
      noMeeting: { da: "Intet møde aftalt.", en: "No meeting agreed." } as I18nText,
      allRequests: { da: "Alle forespørgsler", en: "All requests" } as I18nText,
      queuesTitle: { da: "Køen", en: "The queue" } as I18nText,
      oldest: { da: "ældste {age}", en: "oldest {age}" } as I18nText,
      nothingWaiting: { da: "Intet venter.", en: "Nothing waiting." } as I18nText,
      peopleTitle: { da: "Dem, der venter", en: "Who is waiting" } as I18nText,
      kinds: {
        application: { da: "Ansøgning", en: "Application" },
        access: { da: "Adgang", en: "Access" },
        contact: { da: "Henvendelse", en: "Enquiry" },
        booking: { da: "Møde", en: "Meeting" },
      } as Record<string, I18nText>,
      kpiTitle: { da: "Svartid", en: "Response time" } as I18nText,
      kpiMedian: { da: "Median, 30 dage", en: "Median, 30 days" } as I18nText,
      kpiReplied: { da: "Besvaret, 30 dage", en: "Replied, 30 days" } as I18nText,
      kpiOver: { da: "Over 24 timer", en: "Over 24 hours" } as I18nText,
      seatsTitle: { da: "Pladser i huset", en: "Seats in the house" } as I18nText,
      activityTitle: { da: "Seneste aktivitet", en: "Recent activity" } as I18nText,
      noActivity: { da: "Ingen ændringer endnu.", en: "No changes yet." } as I18nText,
      system: { da: "Systemet", en: "The system" } as I18nText,
      actions: {
        insert: { da: "oprettede", en: "created" },
        update: { da: "ændrede", en: "changed" },
        delete: { da: "slettede", en: "deleted" },
      } as Record<string, I18nText>,
    },
  },
  admin: {
    nav: { da: "Admin", en: "Admin" } as I18nText,
    eyebrow: { da: "Admin", en: "Admin" } as I18nText,
    title: { da: "Husets {em}kontor{/em}", en: "The house {em}office{/em}" } as I18nText,
    intro: {
      da: "Her styrer bestyrelsen adgang, ansøgninger, pladser og tekster. Det første, der virker, er listen over hvem der har adgang.",
      en: "Where the board manages access, applications, seats and copy. The first working part is the list of who has access.",
    } as I18nText,
    peopleTitle: { da: "Hvem har adgang", en: "Who has access" } as I18nText,
    peopleEmpty: { da: "Ingen personer endnu.", en: "No people yet." } as I18nText,
    columns: {
      name: { da: "Navn", en: "Name" } as I18nText,
      email: { da: "E-mail", en: "Email" } as I18nText,
      roles: { da: "Roller", en: "Roles" } as I18nText,
      signedIn: { da: "Konto", en: "Account" } as I18nText,
    },
    linked: { da: "Konto oprettet", en: "Account created" } as I18nText,
    notLinked: { da: "Ingen konto endnu", en: "No account yet" } as I18nText,
  },
  roles: {
    visitor: { da: "Besøgende", en: "Visitor" },
    client: { da: "Kunde", en: "Client" },
    specialist: { da: "Specialist", en: "Specialist" },
    domain_lead: { da: "Domæneansvarlig", en: "Domain lead" },
    board: { da: "Bestyrelse", en: "Board" },
    admin: { da: "Admin", en: "Admin" },
  } as Record<Role, I18nText>,
};
