import type { I18nText } from "@/lib/i18n";

/** Copy for booking requests: the form on the specialist page, Min side, the client's page, the admin list. */
export const bookings = {
  form: {
    eyebrow: { da: "Book et møde", en: "Book a meeting" } as I18nText,
    title: { da: "Tyve minutter med {name}", en: "Twenty minutes with {name}" } as I18nText,
    intro: {
      da: "Foreslå op til tre tidspunkter. {name} svarer på forespørgslen, og I får begge en kalenderinvitation, når tiden er på plads.",
      en: "Propose up to three times. {name} answers the request, and you both get a calendar invitation once the time is set.",
    } as I18nText,
    step: { da: "Trin {n} af 3", en: "Step {n} of 3" } as I18nText,
    duration: { da: "Varighed", en: "Duration" } as I18nText,
    d20: { da: "20 minutter · første møde", en: "20 minutes · first meeting" } as I18nText,
    d45: { da: "45 minutter · gennemgang af opgaven", en: "45 minutes · walk through the brief" } as I18nText,
    times: { da: "Tidspunkter, der passer dig", en: "Times that suit you" } as I18nText,
    timesHint: { da: "Mindst ét, højst tre. Hverdage mellem 8 og 18 fungerer bedst.", en: "At least one, at most three. Weekdays between 8 and 18 work best." } as I18nText,
    timeN: { da: "Forslag {n}", en: "Proposal {n}" } as I18nText,
    next: { da: "Videre", en: "Next" } as I18nText,
    back: { da: "Tilbage", en: "Back" } as I18nText,
    name: { da: "Navn", en: "Name" } as I18nText,
    email: { da: "Arbejdsmail", en: "Work email" } as I18nText,
    company: { da: "Virksomhed (valgfrit)", en: "Company (optional)" } as I18nText,
    brief: { da: "Hvad vil du tale om?", en: "What do you want to talk about?" } as I18nText,
    consent: {
      da: "Jeg accepterer, at TrustUsConsult behandler mine oplysninger for at arrangere mødet.",
      en: "I accept that TrustUsConsult processes my details to arrange the meeting.",
    } as I18nText,
    submit: { da: "Send forespørgsel", en: "Send request" } as I18nText,
    sending: { da: "Sender…", en: "Sending…" } as I18nText,
    doneTitle: { da: "Forespørgslen er sendt.", en: "Request sent." } as I18nText,
    doneText: {
      da: "{name} svarer hurtigst muligt, typisk samme dag. Du får en mail, når tiden er bekræftet, med en kalenderinvitation.",
      en: "{name} replies as soon as possible, usually the same day. You get a mail when the time is confirmed, with a calendar invitation.",
    } as I18nText,
    errors: {
      time: { da: "Vælg mindst ét tidspunkt i fremtiden.", en: "Pick at least one time in the future." } as I18nText,
    },
  },
  status: {
    requested: { da: "Afventer svar", en: "Awaiting reply" },
    accepted: { da: "Aftalt", en: "Agreed" },
    proposed: { da: "Nyt forslag fra specialisten", en: "New proposal from the specialist" },
    declined: { da: "Afslået", en: "Declined" },
    cancelled: { da: "Annulleret", en: "Cancelled" },
  } as Record<string, I18nText>,
  minSide: {
    title: { da: "Mødeforespørgsler", en: "Meeting requests" } as I18nText,
    intro: {
      da: "Svar hurtigt: tiden fra forespørgsel til dit første svar er husets vigtigste tal. Accepter et af tidspunkterne, foreslå et andet, eller afslå.",
      en: "Reply quickly: the time from request to your first reply is the house's headline number. Accept one of the times, propose another, or decline.",
    } as I18nText,
    none: { da: "Ingen forespørgsler endnu.", en: "No requests yet." } as I18nText,
    open: { da: "Åbne", en: "Open" } as I18nText,
    closed: { da: "Afsluttede", en: "Closed" } as I18nText,
    from: { da: "Fra", en: "From" } as I18nText,
    brief: { da: "Om", en: "About" } as I18nText,
    proposedTimes: { da: "Foreslåede tider", en: "Proposed times" } as I18nText,
    accept: { da: "Accepter denne tid", en: "Accept this time" } as I18nText,
    proposeOther: { da: "Foreslå en anden tid", en: "Propose another time" } as I18nText,
    proposeSubmit: { da: "Send forslag", en: "Send proposal" } as I18nText,
    decline: { da: "Afslå", en: "Decline" } as I18nText,
    declineNote: { da: "Kort besked til kunden (valgfrit)", en: "Short message to the client (optional)" } as I18nText,
    accepted: { da: "Aftalt. Begge parter har fået en kalenderinvitation.", en: "Agreed. Both parties got a calendar invitation." } as I18nText,
    proposed: { da: "Forslaget er sendt til kunden.", en: "The proposal is sent to the client." } as I18nText,
    declined: { da: "Afslået. Kunden har fået besked.", en: "Declined. The client has been told." } as I18nText,
    alreadyCancelled: { da: "Kunden har trukket forespørgslen tilbage i mellemtiden. Der er ikke mere at gøre.", en: "The requester has withdrawn the request in the meantime. Nothing more to do." } as I18nText,
    alreadyAccepted: { da: "Tiden er allerede aftalt.", en: "The time is already agreed." } as I18nText,
    replyTime: { da: "Første svar efter {hours} t", en: "First reply after {hours} h" } as I18nText,
    agreedAt: { da: "Aftalt tid", en: "Agreed time" } as I18nText,
  },
  clientPage: {
    eyebrow: { da: "Din mødeforespørgsel", en: "Your meeting request" } as I18nText,
    title: { da: "Møde med {name}", en: "Meeting with {name}" } as I18nText,
    notFound: { da: "Vi kunne ikke finde forespørgslen. Linket kan være brugt eller forkert.", en: "We could not find the request. The link may be used or wrong." } as I18nText,
    yourTimes: { da: "Dine forslag", en: "Your proposals" } as I18nText,
    theirProposal: { da: "{name} foreslår", en: "{name} proposes" } as I18nText,
    acceptProposal: { da: "Ja, den tid passer", en: "Yes, that time works" } as I18nText,
    cancel: { da: "Annuller forespørgslen", en: "Cancel the request" } as I18nText,
    acceptedText: { da: "Tiden er aftalt. Kalenderinvitationen er på vej på mail.", en: "The time is agreed. The calendar invitation is on its way by mail." } as I18nText,
    declinedText: { da: "{name} kunne ikke denne gang. Skriv til huset, så finder vi en anden i domænet.", en: "{name} could not this time. Write to the house and we find someone else in the domain." } as I18nText,
    cancelledText: { da: "Forespørgslen er annulleret.", en: "The request is cancelled." } as I18nText,
    waitingText: { da: "{name} har ikke svaret endnu. Du får en mail, så snart der er nyt.", en: "{name} has not replied yet. You get a mail as soon as there is news." } as I18nText,
    agreed: { da: "Aftalt", en: "Agreed" } as I18nText,
  },
  admin: {
    nav: { da: "Møder", en: "Meetings" } as I18nText,
    title: { da: "Mødeforespørgsler", en: "Meeting requests" } as I18nText,
    intro: {
      da: "Alle forespørgsler i huset, nyeste først, med tiden til specialistens første svar. Bestyrelsen læser; specialisten svarer fra Min side.",
      en: "Every request in the house, newest first, with the time to the specialist's first reply. The board reads; the specialist replies from Min side.",
    } as I18nText,
    specialist: { da: "Specialist", en: "Specialist" } as I18nText,
    client: { da: "Kunde", en: "Client" } as I18nText,
    replyTime: { da: "Svartid", en: "Reply time" } as I18nText,
    noReply: { da: "Intet svar endnu", en: "No reply yet" } as I18nText,
    openCount: { da: "Åbne mødeforespørgsler", en: "Open meeting requests" } as I18nText,
    medianReply: { da: "Median svartid", en: "Median reply time" } as I18nText,
    hours: { da: "{n} t", en: "{n} h" } as I18nText,
  },
};
