import type { I18nText } from "@/lib/i18n";

/** Copy for the specialist pages, Min side and the invitation. */
export const specialists = {
  teaser: {
    years: { da: "{n} år i faget", en: "{n} years in the craft" } as I18nText,
    availableNow: { da: "Ledig nu", en: "Available now" } as I18nText,
    availableFrom: { da: "Ledig fra {date}", en: "Available from {date}" } as I18nText,
    bookedUntil: { da: "Fuldt booket til {date}", en: "Fully booked until {date}" } as I18nText,
    meet: { da: "Mød {name}", en: "Meet {name}" } as I18nText,
    seat: { da: "Plads", en: "Seat" } as I18nText,
  },
  page: {
    back: { da: "Tilbage til domænet", en: "Back to the domain" } as I18nText,
    about: { da: "Om", en: "About" } as I18nText,
    experience: { da: "Erfaring", en: "Experience" } as I18nText,
    education: { da: "Uddannelse", en: "Education" } as I18nText,
    certifications: { da: "Certificeringer", en: "Certifications" } as I18nText,
    skills: { da: "Kompetencer", en: "Skills" } as I18nText,
    languages: { da: "Sprog", en: "Languages" } as I18nText,
    rate: { da: "Takst", en: "Rate" } as I18nText,
    availability: { da: "Ledig", en: "Availability" } as I18nText,
    hoursPerWeek: { da: "{n} timer om ugen", en: "{n} hours a week" } as I18nText,
    contact: { da: "Kontakt", en: "Contact" } as I18nText,
    website: { da: "Hjemmeside", en: "Website" } as I18nText,
    ongoing: { da: "nu", en: "now" } as I18nText,
    gateTitle: { da: "Det fulde CV er for kunder.", en: "The full CV is for clients." } as I18nText,
    gateText: {
      da: "Erfaring, uddannelse, takst og kontakt vises, når du er logget ind som kunde. Skriv til huset, så åbner vi døren.",
      en: "Experience, education, rate and contact appear when you are signed in as a client. Write to the house and we open the door.",
    } as I18nText,
    gateLogin: { da: "Har du adgang? Log ind", en: "Have access? Sign in" } as I18nText,
    gateWrite: { da: "Skriv til huset", en: "Write to the house" } as I18nText,
    gateAsk: { da: "Bed om adgang", en: "Ask for access" } as I18nText,
    gateAskIntro: {
      da: "Fortæl kort, hvem du er, og hvad du leder efter. Bestyrelsen svarer inden for en hverdag, og adgangen gælder alle husets CV'er.",
      en: "Tell us briefly who you are and what you are looking for. The board replies within one working day, and access covers every CV in the house.",
    } as I18nText,
    askName: { da: "Navn", en: "Name" } as I18nText,
    askEmail: { da: "Arbejdsmail", en: "Work email" } as I18nText,
    askCompany: { da: "Virksomhed", en: "Company" } as I18nText,
    askMessage: { da: "Hvad leder du efter?", en: "What are you looking for?" } as I18nText,
    askConsent: {
      da: "Jeg accepterer, at TrustUsConsult behandler mine oplysninger for at behandle min anmodning.",
      en: "I accept that TrustUsConsult processes my details to handle my request.",
    } as I18nText,
    askSubmit: { da: "Send anmodning", en: "Send request" } as I18nText,
    askSending: { da: "Sender…", en: "Sending…" } as I18nText,
    askDoneTitle: { da: "Tak. Vi har din anmodning.", en: "Thanks. We have your request." } as I18nText,
    askDoneText: {
      da: "Bestyrelsen ser på den inden for en hverdag. Får du adgang, kommer der en mail med et link.",
      en: "The board looks at it within one working day. If you get access, a mail with a link follows.",
    } as I18nText,
    book: { da: "Book et møde", en: "Book a meeting" } as I18nText,
    bookSoon: { da: "Mødebooking kommer (2.5). Skriv til huset indtil da.", en: "Booking is coming (2.5). Write to the house until then." } as I18nText,
  },
  minSide: {
    nav: { da: "Min side", en: "My page" } as I18nText,
    eyebrow: { da: "Min side", en: "My page" } as I18nText,
    title: { da: "Din {em}profil{/em}", en: "Your {em}profile{/em}" } as I18nText,
    intro: {
      da: "Det, kunder ser i vinduet og på din side. Dansk er hovedsproget; tomme engelske felter viser det danske.",
      en: "What clients see in the window and on your page. Danish is the main language; empty English fields fall back to Danish.",
    } as I18nText,
    noProfile: {
      da: "Du har ingen profil endnu. Den oprettes, når huset inviterer dig som specialist.",
      en: "You have no profile yet. It is created when the house invites you as a specialist.",
    } as I18nText,
    status: {
      draft: { da: "Kladde: kun du og bestyrelsen ser den.", en: "Draft: only you and the board see it." },
      publishedNoSeat: {
        da: "Udgivet, men din plads er ikke aktiv endnu. Profilen bliver synlig, når bestyrelsen aktiverer pladsen.",
        en: "Published, but your seat is not active yet. The profile goes live when the board activates the seat.",
      },
      live: { da: "Synlig på sitet.", en: "Live on the site." },
    } as Record<string, I18nText>,
    viewPublic: { da: "Se din side", en: "View your page" } as I18nText,
    completeness: { da: "Profilen er {pct} % udfyldt", en: "Profile is {pct} % complete" } as I18nText,
    sections: {
      basics: { da: "Grundlæggende", en: "Basics" } as I18nText,
      about: { da: "Om dig", en: "About you" } as I18nText,
      availability: { da: "Ledighed og takst", en: "Availability and rate" } as I18nText,
      links: { da: "Links", en: "Links" } as I18nText,
      portrait: { da: "Portræt", en: "Portrait" } as I18nText,
      experience: { da: "Erfaring", en: "Experience" } as I18nText,
      education: { da: "Uddannelse", en: "Education" } as I18nText,
      certifications: { da: "Certificeringer", en: "Certifications" } as I18nText,
      publish: { da: "Udgivelse", en: "Publishing" } as I18nText,
      import: { da: "Importér dit CV", en: "Import your CV" } as I18nText,
    },
    fields: {
      title: { da: "Titel", en: "Title" } as I18nText,
      tagline: { da: "Én linje om dig (vises i vinduet)", en: "One line about you (shown in the window)" } as I18nText,
      city: { da: "By", en: "City" } as I18nText,
      years: { da: "År i faget", en: "Years in the craft" } as I18nText,
      summary: { da: "Om dig", en: "About you" } as I18nText,
      skills: { da: "Kompetencer, én per linje", en: "Skills, one per line" } as I18nText,
      languages: { da: "Sprog du arbejder på (fx da, en, de)", en: "Languages you work in (e.g. da, en, de)" } as I18nText,
      rate: { da: "Takst (vises kun for kunder)", en: "Rate (clients only)" } as I18nText,
      weeklyHours: { da: "Timer om ugen til nye opgaver", en: "Hours a week for new work" } as I18nText,
      availableFrom: { da: "Ledig fra", en: "Available from" } as I18nText,
      bookedUntil: { da: "Fuldt booket til", en: "Fully booked until" } as I18nText,
      website: { da: "Egen hjemmeside", en: "Own website" } as I18nText,
      linkedin: { da: "LinkedIn", en: "LinkedIn" } as I18nText,
      slug: { da: "Adresse (/specialister/…)", en: "Address (/specialister/…)" } as I18nText,
      published: { da: "Udgiv profilen", en: "Publish the profile" } as I18nText,
      organisation: { da: "Virksomhed", en: "Organisation" } as I18nText,
      role: { da: "Rolle", en: "Role" } as I18nText,
      description: { da: "Hvad du gjorde", en: "What you did" } as I18nText,
      from: { da: "Fra", en: "From" } as I18nText,
      to: { da: "Til (tom = nu)", en: "To (empty = now)" } as I18nText,
      institution: { da: "Institution", en: "Institution" } as I18nText,
      degree: { da: "Uddannelse", en: "Degree" } as I18nText,
      startYear: { da: "Fra år", en: "From year" } as I18nText,
      endYear: { da: "Til år", en: "To year" } as I18nText,
      certName: { da: "Certificering", en: "Certification" } as I18nText,
      issuer: { da: "Udsteder", en: "Issuer" } as I18nText,
      year: { da: "År", en: "Year" } as I18nText,
    },
    add: { da: "Tilføj", en: "Add" } as I18nText,
    remove: { da: "Fjern", en: "Remove" } as I18nText,
    save: { da: "Gem", en: "Save" } as I18nText,
    saving: { da: "Gemmer…", en: "Saving…" } as I18nText,
    upload: { da: "Upload", en: "Upload" } as I18nText,
    uploading: { da: "Uploader…", en: "Uploading…" } as I18nText,
    portraitHint: { da: "JPG, PNG eller WebP, højst 5 MB. Kvadratisk virker bedst.", en: "JPG, PNG or WebP, up to 5 MB. Square works best." } as I18nText,
    portraitFailed: { da: "Upload mislykkedes. Prøv et mindre billede.", en: "Upload failed. Try a smaller image." } as I18nText,
    importIntro: {
      da: "Upload dit CV som PDF eller indsæt teksten fra din LinkedIn-profil. Huset foreslår felterne; du retter og godkender, før noget gemmes.",
      en: "Upload your CV as a PDF or paste the text from your LinkedIn profile. The house proposes the fields; you correct and approve before anything is saved.",
    } as I18nText,
    importPaste: { da: "Eller indsæt tekst", en: "Or paste text" } as I18nText,
    importRun: { da: "Foreslå felter", en: "Propose fields" } as I18nText,
    importRunning: { da: "Læser…", en: "Reading…" } as I18nText,
    importApply: { da: "Brug forslaget", en: "Use the proposal" } as I18nText,
    importApplied: { da: "Forslaget er lagt ind. Gennemgå og gem felterne ovenfor.", en: "The proposal is in. Review and save the fields above." } as I18nText,
    importUnavailable: {
      da: "CV-import er ikke slået til på serveren endnu (ANTHROPIC_API_KEY mangler).",
      en: "CV import is not enabled on the server yet (ANTHROPIC_API_KEY is missing).",
    } as I18nText,
    importFailed: { da: "Kunne ikke læse CV'et. Prøv med teksten i stedet.", en: "Could not read the CV. Try the text instead." } as I18nText,
  },
  invite: {
    subject: { da: "Din plads i huset", en: "Your seat in the house" } as I18nText,
    title: { da: "Velkommen, {name}.", en: "Welcome, {name}." } as I18nText,
    body: {
      da: [
        "Du er optaget i TrustUsConsult i domænet {domain}, og der er reserveret en plads til dig.",
        "Log ind på {url} med denne e-mailadresse; du får et link tilsendt, ingen adgangskode. Under Min side udfylder du din profil, eller importerer den fra dit CV.",
        "Profilen bliver synlig på sitet, når du udgiver den og bestyrelsen har aktiveret din plads.",
      ],
      en: [
        "You have been admitted to TrustUsConsult in the {domain} domain, and a seat is reserved for you.",
        "Sign in at {url} with this email address; you get a link, no password. Under My page you fill in your profile, or import it from your CV.",
        "The profile goes live when you publish it and the board has activated your seat.",
      ],
    } as Record<"da" | "en", string[]>,
  },
  admin: {
    invite: { da: "Invitér som specialist", en: "Invite as specialist" } as I18nText,
    inviteHint: {
      da: "Opretter personen og kontoen, giver rollen specialist i domænet, reserverer den første åbne plads, opretter en tom profil og sender velkomstmailen.",
      en: "Creates the person and account, grants the specialist role in the domain, reserves the first open seat, creates an empty profile and sends the welcome mail.",
    } as I18nText,
    invited: { da: "Inviteret. Plads {position} er reserveret.", en: "Invited. Seat {position} is reserved." } as I18nText,
    needsDomain: { da: "Ansøgningen har intet domæne. Sæt et under Fag/domæne først.", en: "The application has no domain. Set one first." } as I18nText,
    noSeat: { da: "Ingen åben plads i domænet. Tilføj en under Pladser.", en: "No open seat in the domain. Add one under Seats." } as I18nText,
    alreadyProfile: { da: "Personen har allerede en profil.", en: "The person already has a profile." } as I18nText,
    profiles: { da: "Profiler", en: "Profiles" } as I18nText,
  },
};
